---
- name: Playbook de tâches diverses
  hosts: zac
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy member and convert encoding
      loop:
        - ENSIS00
        - ENSIS01
        # - ENSIS02
        # - ENSIS03
        # - ENSIS04
        # - ENSIS05
        # - ENSIS06
        # - ENSIS07
        # - ENSIS08
        # - ENSIS09
        # - ENSIS10
        # - ENSIS11
        # - ENSIS12
        # - ENSIS13
        # - ENSIS14
        # - ENSIS15
        # - ENSIS16
        # - ENSIS17
        # - ENSIS18
        # - ENSIS19
        # - ENSIS20
        # - ENSIS21
        # - ENSIS22
        # - ENSIS23
        # - ENSIS24
        # - ENSIS25
        # - ENSIS26
        # - ENSIS27
        # - ENSIS28
        # - ENSIS29
        # - ENSIS30
        # - ENSIS31
        # - ENSIS32
        # - ENSIS33
        # - ENSIS34
        # - ENSIS35
        # - ENSIS36
        # - ENSIS37
        # - ENSIS38
        # - ENSIS39
      ibm.ibm_zos_core.zos_copy:
        # On leur donne DECLIExx.cbl + YESPERS.cpy + compilation : CMPDECLI.jcl + run : DECLIENT.jcl
        # TPERSPGM est déjà compilé dans ENSISA.EXEC.LOAD donc pas à toucher
        # en sortie ils doivent donner ENSISA.EXAM.FIC1ETxx
        # On leur donne TPERSPGM.cbl (à copier en TASSURxx) + YESASSUR.cpy + CMPTASxx.jcl
        # Pour le RECASSxx ils se débrouillent, ils repartent de DECLIExx.cbl + compilation + run
        # en sortie ils doivent donner ENSISA.EXAM.FIC2ETxx
        #
        # src: "./zOS/ENSISA/DECLIExx.cbl"
        # dest: ENSISA.EXAM.{{ item }}.SOURCES(DECLIExx)
        # src: "./zOS/ENSISA/YESPERS.cpy"
        # dest: ENSISA.EXAM.{{ item }}.SOURCES(YESPERS)
        # src: "./zOS/ENSISA/CMPDECLI.jcl"
        # dest: ENSISA.EXAM.{{ item }}.JCL(CMPDECLI)
        # src: "./zOS/ENSISA/DECLIENT.jcl"
        # dest: ENSISA.EXAM.{{ item }}.JCL(DECLIENT)
        #
        # src: "./zOS/ENSISA/TPERSPGM.cbl"
        # dest: ENSISA.EXAM.{{ item }}.SOURCES(TPERSPGM)
        # src: "./zOS/ENSISA/YESASSUR.cpy"
        # dest: ENSISA.EXAM.{{ item }}.SOURCES(YESASSUR)
        src: "./zOS/ENSISA/CMPTASxx.jcl"
        dest: ENSISA.EXAM.{{ item }}.JCL(CMPTASxx)
        encoding:
          from: UTF-8
          to: IBM-1140
