---
# TSO command
- name: Execute TSO command list user {{ usertso }}
  ibm.ibm_zos_core.zos_tso_command:
    commands:
      # - LU {{ usertso }}
      - alu {{ usertso }} pa(ZTEC4YOU) resume noexp
      # - LG {{ usertso }}
  register: display

- name: Show display
  ansible.builtin.debug:
    msg: "{{ display }}"
    # msg: "{{ display.output[0].content | regex_search('(USER.*)') }}"
    # msg: "{{ display.output[0].content | select('search', 'USER=|DEFAULT-GROUP=|REVOKE|LAST-ACCESS') }}"