---
- name: Playbook de compilation IMS
  hosts: zt01
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    pgmtocompile: IVTNDB2
    db2prefix: DB2.V12                      # cas mainplex
    # db2prefix: DBC0CFG.DB2.V12              # cas guest zAcademy

  tasks:
    
    # We ask IMS to free the program
    - name: We force MPR to free program ({{ pgmtocompile }})
      ibm.ibm_zos_ims.ims_command:
        command: UPDATE PGM START(REFRESH) NAME({{ pgmtocompile }}) OPTION(ALLRSP)
        # command: UPDATE PGM START(REFRESH) NAME(*) OPTION(ALLRSP)
        # command: UPDATE PGM START(REFRESH) NAME(*)
        plex: IMSC
        route: IMC1
      register: imsout1
      ignore_errors: true
    - name: Resultat de Refresh MPR
      ansible.builtin.debug:
        msg:
          - "Message de sortie": "{{ imsout1.msg }}"
          - "{{ imsout1.ims_output[0].type_2_response[0] }}"

    - name: Compress Directory contents
      ansible.builtin.archive:
        path: 
        - /Users/Aymeric/Documents/Git/ansible-playbooks/IMS/programs/PhoneBook_Db2/*
        dest: /Users/Aymeric/Documents/Git/ansible-playbooks/IMS/programs/PhoneBook.zip  
        format: zip
      delegate_to: 127.0.0.1

    - name: Copy an extract the zip file to z/OS
      ibm.ibm_zos_core.zos_unarchive:
        src: ./IMS/programs/PhoneBook.zip
        dest: "/u/aymeric/SRC_IMS"
        format: 
          name: zip
        force: true

    - name: Change for execution to 80col trailing for files
      ansible.builtin.file:
        path: /u/aymeric/SRC_IMS/iconv_80col.sh
        mode: '0744'

    - name: Execute the command in remote shell
      ansible.builtin.shell: /u/aymeric/SRC_IMS/iconv_80col.sh

    - name: Create temporary directory for the compilation JCL
      ansible.builtin.tempfile:
        state: directory
      register: temp_file_path
      delegate_to: localhost

    - name: Compile templates and put results in temporary directory
      ansible.builtin.template:
        src: "./templates/COIMSDB2_coprocessor_USS.j2"
        dest: "{{ temp_file_path.path }}/COIMSDB2.j2"
        output_encoding: ISO8859-1
        mode: '0644'
      delegate_to: localhost

    - name: Submit compile job
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ temp_file_path.path }}/COIMSDB2.j2"
        location: local
        wait_time_s: 20
        max_rc: 4
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: respcompil
      ignore_errors: true

    - name: Output Soumission Compil
      ansible.builtin.debug:
        msg: "{{ respcompil.jobs[0].ddnames[0].content }}"

    # - name: Job output
    #   ibm.ibm_zos_core.zos_job_output:
    #     job_id: "{{ respcompil.jobs[0].job_id }}"
    #     ddname: "JESMSGLG"
    #   register: outputjob

    # - name: Output Soumission Compil
    #   ansible.builtin.debug:
    #     msg: "{{ outputjob.jobs[0].ddnames[0].content }}"


