---
- name: Bind on Db2 sub system
  hosts: zac
  gather_facts: false
  environment: "{{ environment_vars }}"

# -------
# RAPPEL: PLAN -> COLLECTION -> PACKAGE
# -------

  vars:
    pgmtocompile: 'SE3PICAR'
    dsprefix: 'ENSISA'
    collection: 'CLENSISA'
    schema: 'ENSISA'
    db2sub: 'DBC1'

  tasks:
    - name: Create temporary directory for the compilation JCL
      ansible.builtin.tempfile:
        state: directory
      register: temp_file_path
      delegate_to: localhost

    # Submit JCL
    - name: Compile templates and put results in temporary directory
      ansible.builtin.template:
        src: "./templates/bind.j2"
        dest: "{{ temp_file_path.path }}/bind.j2"
        output_encoding: "ASCII"
        mode: '0644'
      delegate_to: localhost
    - name: Submit JCL
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ temp_file_path.path }}/bind.j2"
        location: LOCAL
        wait_time_s: 2
        return_output: true
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: responsejcl
      # ignore_errors: true
    - name: Display job id
      ansible.builtin.debug:
        msg: "{{ responsejcl.jobs[0].job_id }}"

    - name: Get job output
      ibm.ibm_zos_core.zos_job_output:
        job_id: "{{ responsejcl.jobs[0].job_id }}"
      register: outputcompil
    - name: Display job log
      ansible.builtin.debug:
        msg: "{{ outputcompil.jobs[0].ddnames[0].content }}"
