---
- name: Create Table
  hosts: zt01
  gather_facts: false
  environment: "{{ environment_vars }}"

# -------
# RAPPEL: PLAN -> COLLECTION -> PACKAGE
# -------

  tasks:
    - name: Create temporary directory for the compilation JCL
      ansible.builtin.tempfile:
        state: directory
      register: temp_file_path
      delegate_to: localhost

    # Submit JCL
    - name: Compile templates and put results in temporary directory
      ansible.builtin.template:
        src: "./templates/PhoneBookDDL_Hackathon.jcl"
        dest: "{{ temp_file_path.path }}/PhoneBookDDL.jcl"
        output_encoding: ISO8859-1
        mode: '0644'
      delegate_to: localhost
    - name: Submit JCL
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ temp_file_path.path }}/PhoneBookDDL.jcl"
        location: LOCAL
        wait_time_s: 2
        return_output: true
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: responsejcl
      # ignore_errors: true
    - name: Display job id
      ansible.builtin.debug:
        msg: "{{ responsejcl.jobs[0].job_id }}"

    - name: Get job output
      ibm.ibm_zos_core.zos_job_output:
        job_id: "{{ responsejcl.jobs[0].job_id }}"
      register: outputjob
    - name: Display job log
      ansible.builtin.debug:
        msg: "{{ outputjob }}"
