---
- name: Compilation d'un programme CICS COBOL sans SQL
  hosts: zt01
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars:
    pgmtocompile: 'AAYTEST'
    csdgroup: 'AYMERIC'
    cmci_host: '10.3.20.1'
    cmci_port: '3050'
    cmci_user: 'AYMERIC'
    context: 'MOBPLEX'
    scope: 'CICSMOBP'
    scheme: 'http'

  # vars_prompt:
  #  - name: cmci_user
  #    prompt: CMCI user name (leave blank for unauthenticated)
  #  - name: cmci_password
  #    prompt: CMCI password (leave blank for unauthenticated)

  tasks:
    - name: Copy local progam files to a PDS member
      loop:
        # - { membre: 'API56Q01', fichier: 'API56Q01.cpy' }
        # - { membre: 'API56P01', fichier: 'API56P01.cpy' }
        - { membre: 'AAYTEST', fichier: 'AAYTEST.cbl' }
      ibm.ibm_zos_core.zos_copy:
        src: ./CICS/programs/Test-TopDown-MultiHTTPCode/COBOL/{{ item.fichier }}
        dest: AYMERIC.CICS.SOURCES({{ item.membre }})
        encoding:
          from: UTF-8
          to: IBM-1140
        remote_src: false
        force: true

    - name: Submit compil job
      ibm.ibm_zos_core.zos_job_submit:
        src: ./templates/COMPCCOB.j2
        location: local
        use_template: true
        wait_time_s: 15
        max_rc: 4
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: respcompil

    - name: Output Soumission Compil
      ansible.builtin.debug:
        msg: "{{ respcompil.jobs[0].ddnames[0].content }}"

    - name: Display job id
      ansible.builtin.debug:
        msg: "{{ respcompil.jobs[0].job_id }}"

    - name: NEWCOPY PROGRAM in CICS
      delegate_to: localhost
      ibm.ibm_zos_cics.cmci_action:
        context: '{{ context }}'
        scope: '{{ scope }}'
        cmci_host: '{{ cmci_host }}'
        cmci_port: '{{ cmci_port | int }}'
        cmci_user: '{{ cmci_user | default(omit) }}'
        cmci_password: '{{ cmci_password | default(omit) }}'
        scheme: '{{ scheme }}'
        action_name: NEWCOPY
        type: CICSProgram
        resources:
          filter:
            program: '{{ pgmtocompile }}'
      register: outnewcopy

    - name: Output of the CICS Newcopy
      ansible.builtin.debug:
        msg:
          - { "CMCI failed": "{{ outnewcopy.failed }}",
              "program": "{{ outnewcopy.records[0].program }}",
              "status": "{{ outnewcopy.records[0].status }}" }
