/*****************************************************/
/* Table Contacts pour le schéma PHONEBOOK           */
/*****************************************************/

SELECT * FROM PHONEBOOK.CONTACTS;

SELECT LASTNAME,
       FIRSTNAME,
       PHONE,
       ZIPCODE FROM PHONEBOOK.CONTACTS;


DELETE FROM PHONEBOOK.CONTACTS WHERE FIRSTNAME = 'null';

/*****************************************************/
/* Table Contacts pour le schéma HACKATHON           */
/*****************************************************/

SELECT * FROM HACKATHON.CONTACTS;

SELECT LASTNAME,
       FIRSTNAME,
       PHONE,
       ZIPCODE,
       EMAIL FROM HACKATHON.CONTACTS;

INSERT INTO HACKATHON.CONTACTS  (
                LASTNAME,
                FIRSTNAME,
                PHONE,
                ZIPCODE,
                EMAIL)
                VALUES (
                'AFFOUARD',
                'AYMERIC',
                '0605040302',
                '34000',
                'aymeric@gmail.com');



SELECT * FROM TELECOMN.TYPEEVT;
SELECT * FROM TELECOMN.LIEU;


      FREE PLAN (IVTTELCO) FLAG(I);
      FREE PACKAGE (MOPDBC0.*.IVTTELCO.(*)) FLAG(I);


SELECT DISTINCT AUTHID, AUTHIDTYPE FROM SYSIBMADM.PRIVILEGES 
    WHERE OBJECTNAME = 'CONTACTS' AND OBJECTSCHEMA = 'PHONEBOOK';

SELECT * FROM SYSIBMADM.PRIVILEGES;

SELECT * FROM SYSCAT.SCHEMAAUTH;

SET CURRENT SQLID = 'DB2ADM';
SELECT GRANTEE, ROLENAME, ROLEID FROM SYSIBM.SYSROLEAUTH;



  GRANT DBADM ON DATABASE PBOOKDB TO PUBLIC;
  GRANT USE OF TABLESPACE PBOOKDB.HACKATS TO PUBLIC;
  GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE HACKATHON.CONTACTS
        TO PUBLIC;
  GRANT BIND, EXECUTE ON PLAN IVTNDB2 TO PUBLIC;
  GRANT BIND, EXECUTE ON PACKAGE IVTNDB2.* TO PUBLIC;
  GRANT ALL ON TABLE HACKATHON.CONTACTS TO PUBLIC;