SELECT LASTNAME,
       FIRSTNAME,
       PHONE,
       ZIPCODE FROM PHONEBOOK.CONTACTS;


DELETE FROM PHONEBOOK.CONTACTS WHERE FIRSTNAME ='null';

SELECT * FROM PHONEBOOK.CONTACTS;

SELECT * FROM HACKATHON.CONTACTS;

SELECT * FROM ENSISA.ASSURANCES;

/* 
 TELECOM NANCY :
*/

SELECT * FROM CARBONFP.HEBERGEMENT;

