SELECT * FROM ENSISA.TPERS;


-- DELETE FROM PHONEBOOK.CONTACTS WHERE FIRSTNAME ='null';



SELECT * FROM ENSISA.RAPPEL;


--Projet 09
SELECT * FROM ENSISA.PROJET09;

-- Projet 10
SELECT * FROM ENSISA.TDECLARATION;
SELECT * FROM ENSIS27.V_CLIENTS_RISQUE_NOM;
SELECT * FROM ENSIS27.V_DECL_RISQUE;

-- Projet 11
SELECT * FROM ENSISA.CLIENT_F;